Repository capgoing/FE, pull requests merged in 2025-05, with the labels that each got.

#34 👽 feat: 퀴즈 id 수정
  package-lock.json
  package.json
  src/components/graph/graphFlow.jsx
  src/components/graph/graphMenu.jsx
  src/components/graph/graphNodeAdd.jsx
  src/components/graph/graphNodeEdit.jsx
  src/components/header/header.jsx
  src/components/list/modal/deleteModal.jsx
  src/components/list/modal/modal.jsx
  src/components/list/yesList/item-work.jsx
  src/components/list/yesList/list-work.jsx
  src/components/quiz/quiz/item-quiz.jsx
  src/mocks/graphData.js
  src/pages/graph/graph.jsx
  src/pages/list/list.jsx
  src/styles/graph/graph.jsx
  src/styles/list/list.jsx
Labels: ✨ Feature

#35 🐛 fix: 챗봇 UI 오류 수정
  src/components/graph/chatbot/Chatbot.jsx
  src/components/graph/graphFlow.jsx
  src/pages/graph/graph.jsx
  src/styles/graph/graph.jsx
Labels: 🐞 Bug

#37 ♻️ refactor: 지식그래프 상세 조회 코드 리팩토링 및 챗봇 전송 오류 수정
  src/components/graph/chatbot/Chatbot.jsx
  src/components/graph/graphFlow.jsx
  src/components/graph/graphNode.jsx
  src/contexts/TTSContext.jsx
  src/hooks/useGet.jsx
  src/mocks/graphData.js
  src/styles/common/colors.js
Labels: 🐞 Bug

#42 ♻️ refactor: google tts로 변경
  package-lock.json
  package.json
  src/App.jsx
  src/components/graph/graphFlow.jsx
  src/components/graph/graphNode.jsx
  src/contexts/TTSContext.jsx
  src/layouts/root-layout.jsx
  src/utils/tts.jsx
Labels: 🐞 Bug

#43 🐛 fix: netlify 환경 변수 오류 수정 중
  src/utils/tts.jsx
Labels: 🐞 Bug

#47 ♻️ refactor: 지식 그래프 노드 색상 변경
  src/components/graph/graphFlow.jsx
  src/components/graph/graphNode.jsx
  src/styles/common/colors.js
  src/styles/common/theme.js
  src/styles/graph/graph.jsx
Labels: ✨ Feature

#48 💄 [Style] mainpage iconImg & 애니메이션 추가
  src/assets/images/home/bg.png
  src/assets/images/home/cloud.png
  src/assets/images/home/icon1.png
  src/assets/images/home/icon2.png
  src/pages/home/home.jsx
  src/styles/header/header.jsx
  src/styles/home/home.jsx
Labels: :lipstick: Style

#51 💄 [Style] 메인 페이지 - 배경 CSS 및 페이지 이동 로직 수정
  src/assets/images/home/bg.png
  src/assets/images/home/bg2.svg
  src/assets/images/home/road.png
  src/pages/home/home.jsx
  src/styles/home/home.jsx
Labels: ✨ Feature, :lipstick: Style

#55 ⚡️ [Feature] 챗봇 RAG 모드 적용 추가
  package-lock.json
  package.json
  src/components/graph/chatbot/Chatbot.jsx
  src/styles/graph/graph.jsx
Labels: ✨ Feature, :lipstick: Style

#56 ♻️ refactor: 지식 그래프 형태 수정
  src/assets/images/list/connect.png
  src/assets/images/list/picture.png
  src/components/graph/graphFlow.jsx
  src/components/graph/graphNode.jsx
  src/components/list/yesList/list-work.jsx
  src/mocks/graphData.js
  src/styles/graph/graph.jsx
  src/styles/list/list.jsx
Labels: ✨ Feature

#57 ♻️ refactor: 지식 그래프 형태 수정
  package-lock.json
Labels: ✨ Feature

#71 🎨 design: 폰트 수정
  src/components/graph/graphFlow.jsx
  src/components/graph/graphNode.jsx
  src/components/list/modal/Loading.jsx
  src/styles/home/home.jsx
Labels: 🐞 Bug

#75 🐛 fix: 그래프 노드 확대 오류 수정 중
  src/components/graph/graphFlow.jsx
Labels: 🐞 Bug
